chore(scripts): Add warning to stderr when Homebrew cannot be found

diff --git a/run_after_A-homebrew-sync.sh.tmpl b/run_after_A-homebrew-sync.sh.tmpl
--- a/run_after_A-homebrew-sync.sh.tmpl
+++ b/run_after_A-homebrew-sync.sh.tmpl
@@ -8,6 +8,7 @@ if [ "$(uname -s)" != Darwin ]; then
 fi
 
 if ! command -v brew > /dev/null; then
+  echo >&2 'WARNING: Could not find brew; installing...'
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 fi
 
